output_dir: ./outputs/benchmarks_tmp
batch_size: 8
device: cpu
mlflow_tracking: false
perplexity:
  data_path: ./data/processed/oas_real_full
  batch_size: 8
  max_samples: 8
liability:
  data_path: ./data/processed/oas_real_full
  batch_size: 8
  max_samples: 8
  liability_features:
    - nglyc
    - deamidation
    - isomerization
    - oxidation
    - free_cysteines
developability:
  data_path: ./data/processed/therapeutic_benchmark/therapeutic_benchmark.parquet
  batch_size: 4
  max_samples: 8
zero_shot:
  data_path: ./data/processed/zero_shot/zero_shot.parquet
  batch_size: 4
  max_samples: 8
