output_dir: ./outputs/benchmarks
batch_size: 8
device: cpu
mlflow_tracking: false

baselines:
  esm2:
    model:
      model_name: esm2_t6_8M_UR50D
      repr_layer: 6
      probe_dropout: 0.1
      freeze_backbone: true
      tasks: ["mlm", "cls", "reg"]
      sequence_pooling: mean
      liability_keys:
        - nglyc
        - deamidation
    training:
      data_path: ./data/processed/oas_real
      train_split: val
      val_split: val
      batch_size: 2
      num_workers: 0
      learning_rate: 1.0e-3
      weight_decay: 0.0
      grad_clip: 1.0
      output_dir: ./outputs/esm2_probes_tiny
      checkpoint_name: best.pt
      tasks: ["mlm", "cls", "reg"]
    evaluation:
      batch_size: 4
      device: cpu
      runtime_tracking: false
      memory_tracking: false
      html_report: false
      output_dir: ./outputs/esm2_benchmarks_tiny

perplexity:
  data_path: ./data/processed/oas_real
  batch_size: 4
  max_samples: 64
