# Transformer model defaults.
vocab_size: 25  # 4 specials + 21 amino acid tokens
d_model: 384
nhead: 6
num_layers: 3
dim_feedforward: 1536
dropout: 0.1
max_position_embeddings: 1024
liability_keys:
  - nglyc
  - deamidation
  - isomerization
  - oxidation
  - free_cysteines
task_weights:
  mlm: 1.0
  cls: 1.0
  reg: 1.0
